apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:openshift-service-catalog-apiserver-remover
  annotations:
    release.openshift.io/delete: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: openshift-service-catalog-removed
  name: openshift-service-catalog-apiserver-remover
